//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExhaustiveSwitch.Analyzer {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExhaustiveSwitch.Analyzer.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All concrete types with [Case] attribute must be explicitly handled..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch does not handle '{1}' case of Exhaustive type '{0}'..
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exhaustiveness violation.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add all missing cases.
        /// </summary>
        internal static string CodeFixAddAllCases {
            get {
                return ResourceManager.GetString("CodeFixAddAllCases", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add '{0}' case.
        /// </summary>
        internal static string CodeFixAddSingleCase {
            get {
                return ResourceManager.GetString("CodeFixAddSingleCase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add individual cases....
        /// </summary>
        internal static string CodeFixAddIndividualCases {
            get {
                return ResourceManager.GetString("CodeFixAddIndividualCases", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Case without Exhaustive base.
        /// </summary>
        internal static string OrphanCaseTitle {
            get {
                return ResourceManager.GetString("OrphanCaseTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type '{0}' has [Case] attribute but does not implement or inherit any [Exhaustive] type..
        /// </summary>
        internal static string OrphanCaseMessageFormat {
            get {
                return ResourceManager.GetString("OrphanCaseMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Types with [Case] attribute should implement or inherit at least one type with [Exhaustive] attribute..
        /// </summary>
        internal static string OrphanCaseDescription {
            get {
                return ResourceManager.GetString("OrphanCaseDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exhaustive enum violation.
        /// </summary>
        internal static string EnumAnalyzerTitle {
            get {
                return ResourceManager.GetString("EnumAnalyzerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch does not handle '{1}' member of Exhaustive enum '{0}'..
        /// </summary>
        internal static string EnumAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EnumAnalyzerMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All enum members must be explicitly handled in switch statements on enums with [Exhaustive] attribute..
        /// </summary>
        internal static string EnumAnalyzerDescription {
            get {
                return ResourceManager.GetString("EnumAnalyzerDescription", resourceCulture);
            }
        }
    }
}
